const BSC = {
    TOKEN: require("../tokens/bsc/token"),
    V1ABI: require("../abi/farms/bsc/v1"),
    BBLLP: require("../tokens/bsc/bbllp"),
};

const ETH = {
    BBLTOKEN: require("../tokens/eth/bbl"),
    BBLLP: require("../tokens/eth/bbllp"),
    V1ABI: require("../abi/farms/eth/v1"),
};

module.exports = [
    {
        id: "eth",
        name: "STAKE PBL FOR PBL",
        type: "token",
        startTime: 167294799800,
        duration: 365,
        early_fee: 5,
        token: ETH.BBLTOKEN,
        APR_MULTIPLER: 1,
        network: 1,
        abi: ETH.V1ABI,
        contract: "0xbe49671F4694094cd8cD001834DfD85bf86D5C32",
        harvestToken: false,
        past: false,
        rewardToken: "PBL",
    },
    // {
    //     id: "PBL",
    //     name: "STAKE PBL FOR WPOM",
    //     type: "token",
    //     startTime: 167260688900,
    //     duration: 60,
    //     early_fee: 7,
    //     early_fee_percent: 25,
    //     token: BSC.TOKEN,
    //     APR_MULTIPLER: 1,
    //     network: 18159,
    //     abi: BSC.V1ABI,
    //     contract: "0x4ad6D6C180E092266D9f65A27E19FF69e7441D2F",
    //     harvestToken: false,
    //     past: true,
    //     rewardToken: "WPOM",
    // },
    {
        id: "PBLLP",
        name: "STAKE PBL/BNB PAIR FOR PBL",
        type: "token",
        startTime: 167446727400,
        duration: 365,
        early_fee: 7,
        early_fee_percent: 25,
        token: BSC.BBLLP,
        APR_MULTIPLER: 1,
        network: 56,
        abi: BSC.V1ABI,
        contract: "0x922d5128f56fE86f857D3Ef7cDA9287486328842",
        lp_contract: {
            address: "0x2F8b6b52af6f761335d1fC59593709f7Cf7A4F00",
            abi: require("../abi/farms/bsc/lp"),
        },
        harvestToken: "PBL",
        harvestTokenData: BSC.BBLTOKEN,
        past: false,
        rewardToken: "PBL",
    },
    // {
    //     id: "PBL90",
    //     name: "POOL CLOSED",
    //     type: "token",
    //     startTime: 167128787700,
    //     duration: 90,
    //     early_fee: 90,
    //     early_fee_percent: 25,
    //     token: BSC.TOKEN,
    //     APR_MULTIPLER: 1,
    //     network: 18159,
    //     abi: BSC.V1ABI,
    //     contract: "0x653D39b120f2D00754C1E56448Aac94CF6162DEb",
    //     harvestToken: false,
    //     past: true,
    //     rewardToken: "PBL",
    // }, 
    // {
    //     id: "PBLC",
    //     name: "POOL CLOSED",
    //     type: "token",
    //     startTime: 167376435300,
    //     duration: 10,
    //     early_fee: 2,
    //     early_fee_percent: 25,
    //     token: BSC.TOKEN,
    //     APR_MULTIPLER: 143,
    //     network: 18159,
    //     abi: BSC.V1ABI,
    //     contract: "0xcba2FEdd5eECe601c11984DeaCDb6F6E15c7b716",
    //     harvestToken: false,
    //     past: true,
    //     rewardToken: "POM",
    // },
];
