module.exports = [
    { type: "constructor", stateMutability: "nonpayable", inputs: [] },
    {
        type: "event",
        name: "Approval",
        inputs: [
            {
                type: "address",
                name: "owner",
                internalType: "address",
                indexed: true,
            },
            {
                type: "address",
                name: "spender",
                internalType: "address",
                indexed: true,
            },
            {
                type: "uint256",
                name: "value",
                internalType: "uint256",
                indexed: false,
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Fees",
        inputs: [
            {
                type: "uint256",
                name: "_marketingBuy",
                internalType: "uint256",
                indexed: false,
            },
            {
                type: "uint256",
                name: "_liqBuy",
                internalType: "uint256",
                indexed: false,
            },
            {
                type: "uint256",
                name: "_farmingBuy",
                internalType: "uint256",
                indexed: false,
            },
            {
                type: "uint256",
                name: "_marketingSell",
                internalType: "uint256",
                indexed: false,
            },
            {
                type: "uint256",
                name: "_liqSell",
                internalType: "uint256",
                indexed: false,
            },
            {
                type: "uint256",
                name: "_farmingSell",
                internalType: "uint256",
                indexed: false,
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnershipTransferred",
        inputs: [
            {
                type: "address",
                name: "previousOwner",
                internalType: "address",
                indexed: true,
            },
            {
                type: "address",
                name: "newOwner",
                internalType: "address",
                indexed: true,
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SendNative",
        inputs: [
            {
                type: "bool",
                name: "_wallet",
                internalType: "bool",
                indexed: false,
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            {
                type: "address",
                name: "from",
                internalType: "address",
                indexed: true,
            },
            {
                type: "address",
                name: "to",
                internalType: "address",
                indexed: true,
            },
            {
                type: "uint256",
                name: "value",
                internalType: "uint256",
                indexed: false,
            },
        ],
        anonymous: false,
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
        name: "allowance",
        inputs: [
            { type: "address", name: "owner", internalType: "address" },
            { type: "address", name: "spender", internalType: "address" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "approve",
        inputs: [
            { type: "address", name: "spender", internalType: "address" },
            { type: "uint256", name: "amount", internalType: "uint256" },
        ],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
        name: "balanceOf",
        inputs: [{ type: "address", name: "account", internalType: "address" }],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "burn",
        inputs: [{ type: "uint256", name: "amount", internalType: "uint256" }],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "uint8", name: "", internalType: "uint8" }],
        name: "decimals",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "decreaseAllowance",
        inputs: [
            { type: "address", name: "spender", internalType: "address" },
            {
                type: "uint256",
                name: "subtractedValue",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "address", name: "", internalType: "address" }],
        name: "farmingAddress",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "feeExempt",
        inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [
            { type: "uint256", name: "marketingBuy", internalType: "uint256" },
            { type: "uint256", name: "liqBuy", internalType: "uint256" },
            { type: "uint256", name: "farmingBuy", internalType: "uint256" },
            { type: "uint256", name: "marketingSell", internalType: "uint256" },
            { type: "uint256", name: "liqSell", internalType: "uint256" },
            { type: "uint256", name: "farmingSell", internalType: "uint256" },
        ],
        name: "getFees",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [
            { type: "uint256", name: "buys", internalType: "uint256" },
            { type: "uint256", name: "sells", internalType: "uint256" },
            { type: "uint256", name: "lastTx", internalType: "uint256" },
        ],
        name: "getRecentTx",
        inputs: [
            { type: "address", name: "_address", internalType: "address" },
        ],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [
            { type: "uint256", name: "buyLimit", internalType: "uint256" },
            { type: "uint256", name: "sellLimit", internalType: "uint256" },
            { type: "uint256", name: "cooldown", internalType: "uint256" },
            { type: "bool", name: "inactive", internalType: "bool" },
        ],
        name: "getTxLimits",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "increaseAllowance",
        inputs: [
            { type: "address", name: "spender", internalType: "address" },
            { type: "uint256", name: "addedValue", internalType: "uint256" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "manualSendNative",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "manualSwapTokensForNative",
        inputs: [{ type: "uint256", name: "_amount", internalType: "uint256" }],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "string", name: "", internalType: "string" }],
        name: "name",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "address", name: "", internalType: "address" }],
        name: "nativeToken",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "address", name: "", internalType: "address" }],
        name: "nativeTokenAddress",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "address", name: "", internalType: "address" }],
        name: "owner",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "renounceOwnership",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "setFeeExempt",
        inputs: [
            { type: "address", name: "_address", internalType: "address" },
            { type: "bool", name: "_value", internalType: "bool" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "setFees",
        inputs: [
            { type: "uint256", name: "_marketingBuy", internalType: "uint256" },
            { type: "uint256", name: "_liqBuy", internalType: "uint256" },
            { type: "uint256", name: "_farmingBuy", internalType: "uint256" },
            {
                type: "uint256",
                name: "_marketingSell",
                internalType: "uint256",
            },
            { type: "uint256", name: "_liqSell", internalType: "uint256" },
            { type: "uint256", name: "_farmingSell", internalType: "uint256" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "setSwapTokens",
        inputs: [
            { type: "uint256", name: "_swapTokensAt", internalType: "uint256" },
            { type: "uint256", name: "_lastSwap", internalType: "uint256" },
            { type: "uint256", name: "_delay", internalType: "uint256" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "setTaxAddress",
        inputs: [
            {
                type: "address",
                name: "_farmingAddress",
                internalType: "address",
            },
            { type: "address", name: "_taxAddress", internalType: "address" },
            {
                type: "address",
                name: "_nativeTokenAddress",
                internalType: "address",
            },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "setTxLimitExempt",
        inputs: [
            { type: "address", name: "_address", internalType: "address" },
            { type: "bool", name: "_value", internalType: "bool" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "setTxLimits",
        inputs: [
            { type: "uint256", name: "_buyLimit", internalType: "uint256" },
            { type: "uint256", name: "_sellLimit", internalType: "uint256" },
            { type: "uint256", name: "_cooldown", internalType: "uint256" },
            { type: "bool", name: "_inactive", internalType: "bool" },
        ],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [
            { type: "uint256", name: "swapTokensAt", internalType: "uint256" },
            { type: "uint256", name: "lastSwap", internalType: "uint256" },
            { type: "uint256", name: "swapDelay", internalType: "uint256" },
            { type: "uint256", name: "minToSend", internalType: "uint256" },
        ],
        name: "swapTokens",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "string", name: "", internalType: "string" }],
        name: "symbol",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "address", name: "", internalType: "address" }],
        name: "taxAddress",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
        name: "totalSupply",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "transfer",
        inputs: [
            { type: "address", name: "to", internalType: "address" },
            { type: "uint256", name: "amount", internalType: "uint256" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "transferFrom",
        inputs: [
            { type: "address", name: "from", internalType: "address" },
            { type: "address", name: "to", internalType: "address" },
            { type: "uint256", name: "amount", internalType: "uint256" },
        ],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "transferOwnership",
        inputs: [
            { type: "address", name: "newOwner", internalType: "address" },
        ],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "bool", name: "", internalType: "bool" }],
        name: "txLimitExempt",
        inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [{ type: "address", name: "", internalType: "address" }],
        name: "uniswapV2Pair",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "view",
        outputs: [
            {
                type: "address",
                name: "",
                internalType: "contract IUniswapV2Router02",
            },
        ],
        name: "uniswapV2Router",
        inputs: [],
    },
    {
        type: "function",
        stateMutability: "nonpayable",
        outputs: [],
        name: "withdrawAnyToken",
        inputs: [
            { type: "address", name: "_to", internalType: "address payable" },
            {
                type: "address",
                name: "_token",
                internalType: "contract IERC20",
            },
        ],
    },
    { type: "receive", stateMutability: "payable" },
];
